/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    vendors: Vendor;
    categories: Category;
    products: Product;
    orders: Order;
    quotes: Quote;
    pages: Page;
    media: Media;
    payouts: Payout;
    refunds: Refund;
    'processed-events': ProcessedEvent;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    payouts: PayoutsSelect<false> | PayoutsSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    'processed-events': ProcessedEventsSelect<false> | ProcessedEventsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'vendor' | 'customer';
  /**
   * The vendor this user is associated with (required for vendor role).
   */
  vendor?: (number | null) | Vendor;
  phone?: string | null;
  marketingOptIn?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  name: string;
  slug: string;
  status: 'pending' | 'active' | 'paused' | 'banned';
  /**
   * Short one-line description shown on storefront card.
   */
  tagline?: string | null;
  bio?: string | null;
  logo?: (number | null) | Media;
  country?: string | null;
  city?: string | null;
  /**
   * Platform commission % on this vendor's sales. Admin-only.
   */
  commissionRate?: number | null;
  payout?: {
    method?: ('bank' | 'stripe_connect' | 'flutterwave_sub') | null;
    bankName?: string | null;
    accountHolder?: string | null;
    accountNumber?: string | null;
    swiftBic?: string | null;
    stripeConnectAccountId?: string | null;
    flutterwaveSubAccountId?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  /**
   * Display order in nav (lower first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  vendor: number | Vendor;
  status: 'draft' | 'pending' | 'published' | 'archived';
  /**
   * Retail items check out instantly via Stripe/Flutterwave. Quote items go through the B2B quote flow.
   */
  fulfillmentMode: 'retail' | 'quote' | 'hybrid';
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Price in minor units (cents). e.g. 12500 = 125.00.
   */
  priceMinor: number;
  /**
   * Was-price in minor units. Optional.
   */
  compareAtMinor?: number | null;
  currency: 'NAD' | 'ZAR' | 'USD' | 'GBP' | 'EUR';
  /**
   * Internal SKU. Auto-generated if blank.
   */
  sku?: string | null;
  inventory?: {
    trackQuantity?: boolean | null;
    quantity?: number | null;
    allowBackorder?: boolean | null;
    lowStockThreshold?: number | null;
  };
  shipping?: {
    weightGrams?: number | null;
    lengthCm?: number | null;
    widthCm?: number | null;
    heightCm?: number | null;
    requiresShipping?: boolean | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  /**
   * Unguessable secret used to gate guest order viewing. Never exposed in lists.
   */
  confirmationToken: string;
  status: 'pending_payment' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded' | 'disputed';
  customer?: (number | null) | User;
  /**
   * For guest checkouts (no account).
   */
  guestEmail?: string | null;
  lineItems?:
    | {
        product: number | Product;
        vendor: number | Vendor;
        titleSnapshot: string;
        skuSnapshot?: string | null;
        quantity: number;
        unitPriceMinor: number;
        lineTotalMinor: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Set by createOrderFromCart when stock was deducted at creation. Cancelled orders only restore stock when this is true.
   */
  inventoryDecremented?: boolean | null;
  subtotalMinor: number;
  shippingMinor?: number | null;
  taxMinor?: number | null;
  discountMinor?: number | null;
  totalMinor: number;
  currency: 'NAD' | 'ZAR' | 'USD' | 'GBP' | 'EUR';
  payment?: {
    processor?: ('stripe' | 'flutterwave' | 'manual') | null;
    processorRef?: string | null;
    /**
     * Inner Stripe PaymentIntent id (pi_…) used to match refund webhooks.
     */
    processorIntentRef?: string | null;
    paidAt?: string | null;
  };
  shippingAddress?: {
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  billingAddress?: {
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  fulfillment?: {
    carrier?: string | null;
    trackingNumber?: string | null;
    shippedAt?: string | null;
    deliveredAt?: string | null;
  };
  /**
   * Internal notes — not shown to customer.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * B2B / bulk enquiry quotes. Convertible into orders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  quoteNumber: string;
  /**
   * Unguessable token gating the quote-acceptance URL.
   */
  confirmationToken: string;
  status: 'submitted' | 'reviewing' | 'quoted' | 'accepted' | 'declined' | 'converted' | 'expired';
  customer?: (number | null) | User;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  companyName?: string | null;
  destinationCountry?: string | null;
  items?:
    | {
        product: number | Product;
        vendor: number | Vendor;
        titleSnapshot: string;
        quantity: number;
        notes?: string | null;
        /**
         * Vendor/admin sets the quoted unit price.
         */
        unitPriceQuoteMinor?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Quoted total. Filled in once vendor responds.
   */
  totalEstimateMinor?: number | null;
  currency?: string | null;
  /**
   * Original customer message.
   */
  message?: string | null;
  response?: {
    message?: string | null;
    respondedBy?: (number | null) | User;
    respondedAt?: string | null;
    /**
     * Quote expires after this date.
     */
    validUntil?: string | null;
  };
  /**
   * If accepted, the order created from this quote.
   */
  convertedOrder?: (number | null) | Order;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Vendor payouts ledger. Admin generates statements from paid orders and records bank transfers here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payouts".
 */
export interface Payout {
  id: number;
  /**
   * Bank transfer reference / Stripe transfer ID / payment ref.
   */
  reference: string;
  vendor: number | Vendor;
  status: 'pending' | 'processing' | 'paid' | 'cancelled';
  /**
   * Inclusive start of the period this statement covers.
   */
  periodStart: string;
  /**
   * Inclusive end of the period.
   */
  periodEnd: string;
  lines?:
    | {
        orderRef: number | Order;
        /**
         * Captured at statement generation time.
         */
        orderNumberSnapshot: string;
        paidAt?: string | null;
        /**
         * Vendor revenue on this order before commission.
         */
        grossMinor: number;
        /**
         * Platform commission deducted.
         */
        commissionMinor: number;
        /**
         * Net owed to vendor (gross - commission).
         */
        payoutMinor: number;
        id?: string | null;
      }[]
    | null;
  totalGrossMinor: number;
  totalCommissionMinor: number;
  /**
   * Net amount transferred to the vendor.
   */
  totalPayoutMinor: number;
  currency: 'NAD' | 'ZAR' | 'USD' | 'GBP' | 'EUR';
  /**
   * When the transfer actually cleared.
   */
  paidAt?: string | null;
  /**
   * Internal notes (not surfaced to vendor).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer refunds. Linked to an order. Updating to status=completed marks the order refunded.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: number;
  /**
   * Internal reference / processor refund id.
   */
  reference: string;
  order: number | Order;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  /**
   * Refund amount in minor units (cents).
   */
  amountMinor: number;
  currency: 'NAD' | 'ZAR' | 'USD' | 'GBP' | 'EUR';
  reason: 'requested_by_customer' | 'quality' | 'out_of_stock' | 'lost_in_transit' | 'fraud' | 'other';
  /**
   * Free-text notes — visible to customer.
   */
  description?: string | null;
  /**
   * How the refund was issued.
   */
  processor?: ('stripe' | 'flutterwave' | 'manual') | null;
  /**
   * Processor refund id (re_… for Stripe, etc.)
   */
  processorRef?: string | null;
  /**
   * Captured from the order at creation time.
   */
  customer?: (number | null) | User;
  /**
   * Primary vendor on the original order (for scoping).
   */
  vendorRef?: (number | null) | Vendor;
  /**
   * When funds actually returned to the customer.
   */
  refundedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Webhook idempotency ledger. Read-only for vendors; admin can prune.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processed-events".
 */
export interface ProcessedEvent {
  id: number;
  key: string;
  processor: 'stripe' | 'flutterwave';
  /**
   * Event type, e.g. checkout.session.completed
   */
  kind?: string | null;
  /**
   * Order ID resolved during handling (if any).
   */
  orderId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only audit trail. Populated by collection hooks; never edited directly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  kind:
    | 'order.created'
    | 'order.status_changed'
    | 'refund.created'
    | 'refund.completed'
    | 'vendor.approved'
    | 'vendor.status_changed'
    | 'product.price_changed'
    | 'product.status_changed'
    | 'inventory.revert_failed'
    | 'user.role_changed'
    | 'user.sessions_revoked'
    | 'payout.status_changed'
    | 'user.deleted';
  /**
   * Collection slug the action targets (orders, refunds, …).
   */
  subjectType: string;
  subjectId: string;
  /**
   * User id, or "system" for hook-initiated events.
   */
  actorId?: string | null;
  /**
   * Captured at write time for forensic lookup.
   */
  actorEmail?: string | null;
  actorRole?: ('admin' | 'vendor' | 'customer' | 'system') | null;
  /**
   * Snapshot of what changed: { before: {…}, after: {…} } where applicable.
   */
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'payouts';
        value: number | Payout;
      } | null)
    | ({
        relationTo: 'refunds';
        value: number | Refund;
      } | null)
    | ({
        relationTo: 'processed-events';
        value: number | ProcessedEvent;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  vendor?: T;
  phone?: T;
  marketingOptIn?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  tagline?: T;
  bio?: T;
  logo?: T;
  country?: T;
  city?: T;
  commissionRate?: T;
  payout?:
    | T
    | {
        method?: T;
        bankName?: T;
        accountHolder?: T;
        accountNumber?: T;
        swiftBic?: T;
        stripeConnectAccountId?: T;
        flutterwaveSubAccountId?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  vendor?: T;
  status?: T;
  fulfillmentMode?: T;
  shortDescription?: T;
  description?: T;
  categories?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  priceMinor?: T;
  compareAtMinor?: T;
  currency?: T;
  sku?: T;
  inventory?:
    | T
    | {
        trackQuantity?: T;
        quantity?: T;
        allowBackorder?: T;
        lowStockThreshold?: T;
      };
  shipping?:
    | T
    | {
        weightGrams?: T;
        lengthCm?: T;
        widthCm?: T;
        heightCm?: T;
        requiresShipping?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  confirmationToken?: T;
  status?: T;
  customer?: T;
  guestEmail?: T;
  lineItems?:
    | T
    | {
        product?: T;
        vendor?: T;
        titleSnapshot?: T;
        skuSnapshot?: T;
        quantity?: T;
        unitPriceMinor?: T;
        lineTotalMinor?: T;
        id?: T;
      };
  inventoryDecremented?: T;
  subtotalMinor?: T;
  shippingMinor?: T;
  taxMinor?: T;
  discountMinor?: T;
  totalMinor?: T;
  currency?: T;
  payment?:
    | T
    | {
        processor?: T;
        processorRef?: T;
        processorIntentRef?: T;
        paidAt?: T;
      };
  shippingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  billingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  fulfillment?:
    | T
    | {
        carrier?: T;
        trackingNumber?: T;
        shippedAt?: T;
        deliveredAt?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  confirmationToken?: T;
  status?: T;
  customer?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  companyName?: T;
  destinationCountry?: T;
  items?:
    | T
    | {
        product?: T;
        vendor?: T;
        titleSnapshot?: T;
        quantity?: T;
        notes?: T;
        unitPriceQuoteMinor?: T;
        id?: T;
      };
  totalEstimateMinor?: T;
  currency?: T;
  message?: T;
  response?:
    | T
    | {
        message?: T;
        respondedBy?: T;
        respondedAt?: T;
        validUntil?: T;
      };
  convertedOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payouts_select".
 */
export interface PayoutsSelect<T extends boolean = true> {
  reference?: T;
  vendor?: T;
  status?: T;
  periodStart?: T;
  periodEnd?: T;
  lines?:
    | T
    | {
        orderRef?: T;
        orderNumberSnapshot?: T;
        paidAt?: T;
        grossMinor?: T;
        commissionMinor?: T;
        payoutMinor?: T;
        id?: T;
      };
  totalGrossMinor?: T;
  totalCommissionMinor?: T;
  totalPayoutMinor?: T;
  currency?: T;
  paidAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  reference?: T;
  order?: T;
  status?: T;
  amountMinor?: T;
  currency?: T;
  reason?: T;
  description?: T;
  processor?: T;
  processorRef?: T;
  customer?: T;
  vendorRef?: T;
  refundedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processed-events_select".
 */
export interface ProcessedEventsSelect<T extends boolean = true> {
  key?: T;
  processor?: T;
  kind?: T;
  orderId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  kind?: T;
  subjectType?: T;
  subjectId?: T;
  actorId?: T;
  actorEmail?: T;
  actorRole?: T;
  diff?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headlineLeading?: string | null;
    headlineTrailing?: string | null;
    subhead?: string | null;
  };
  /**
   * Order matters. Shown on homepage and feeds.
   */
  featuredProducts?: (number | Product)[] | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headlineLeading?: T;
        headlineTrailing?: T;
        subhead?: T;
      };
  featuredProducts?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}